#ifndef CORETYPE_H
#define CORETYPE_H

namespace zerO
{
	typedef enum
	{
		RESOURCE_VERTEX_BUFFER = 0,
		RESOURCE_INDEX_BUFFER,
		RESOURCE_TEXTURE,
		RESOURCE_SURFACE,
		RESOURCE_EFFECT,
		RESOURCE_MESH,
		RESOURCE_MODEL,
		RESOURCE_ANIMATIONCONTROLLER,
		RESUORCE_FULLSCREENEFFECT,
		RESOURCE_TEXTUREPRINTER,

		TOTAL_RESOURCE_TYPES
	}RESOURCETYPE;

	typedef UINT16 RESOURCEHANDLE;
}

#endif